package Bar;

/**
 * Enum for the drinks.
 */
public enum Drinks {
    NEGRONI,SPRITZ,REDBULLVODKA,LONGISLANDICEDTEA,SEXONTHEBEACH,OLDFASHIONED,
    MARGARITA,COSMOPOLITAN,MARTINI,MOJITO,ONEMILIONBEERS,BEERANDCARKEYS
}
